/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psbd.projekt.panes;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Michal
 */
public class HotelObl extends javax.swing.JPanel {

    int id_hotelu;
    Oblozenie parentDialog;
    ArrayList<PokojObl> pokoje = new ArrayList<>();
    JPanel p = new JPanel();
    int oblozenieInt = 0;

    /**
     * Creates new form HotelNiezre
     */
    public HotelObl(int id_hotelu, String nazwa, int liczbaGw, Oblozenie parentDialog) {
        initComponents();
        this.id_hotelu = id_hotelu;
        this.parentDialog = parentDialog;
        lblNazwa.setText(nazwa);
        String str = "";
        for (int i = 0; i < liczbaGw; ++i) {
            str += "*";
        }
        lblIoscGwiazdek.setText(str);
    }

    public int getOblozenie() {
        return oblozenieInt;
    }

    public int getIdHotelu() {
        return id_hotelu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblNazwa = new javax.swing.JLabel();
        lblIoscGwiazdek = new javax.swing.JLabel();
        lblObl = new javax.swing.JLabel();

        jButton1.setText("Anuluj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblNazwa.setText("Nazwa");

        lblIoscGwiazdek.setText("***");

        lblObl.setText("Oblozenie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNazwa)
                        .addGap(18, 18, 18)
                        .addComponent(lblIoscGwiazdek)
                        .addGap(37, 37, 37)
                        .addComponent(lblObl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblNazwa)
                    .addComponent(lblIoscGwiazdek)
                    .addComponent(lblObl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIoscGwiazdek;
    private javax.swing.JLabel lblNazwa;
    private javax.swing.JLabel lblObl;
    // End of variables declaration//GEN-END:variables

    public void addPokoj(int standard, int liczba_osob, int ile_rezerwacji) {
        PokojObl pn = new PokojObl(standard, liczba_osob, ile_rezerwacji);
        pokoje.add(pn);
    }

    void renderuj() {
        int size = pokoje.size();
        p.setLayout(new GridLayout(size, 1));
        for (int i = 0; i < size; ++i) {
            oblozenieInt += pokoje.get(i).getOblozenie();
            p.add(pokoje.get(i));
        }
        lblObl.setText("Oblożenie: " + oblozenieInt);
        jScrollPane1.setViewportView(p);
        jScrollPane1.validate();
        jScrollPane1.repaint();
    }
}
