/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package psbd.projekt.panes;

import java.awt.GridLayout;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JPanel;
import psbd.projekt.model.OblozenieKlasa;
import psbd.projekt.model.RaportyDialog;
import psbd.projekt.utils.MySql;

/**
 *
 * @author Michal
 */
public class Oblozenie extends javax.swing.JPanel {
    
    JPanel p = new JPanel();
    private RaportyDialog parentFrame;
    
    /**
     * Creates new form Obłozenie
     */
    public Oblozenie(RaportyDialog parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOblozenie = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jLabel1.setText("Okres:");

        lblOblozenie.setText("Suma obłożenia");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard hotelu", "Obłożenie hotelu" }));

        jButton1.setText("Sortuj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(229, 229, 229)
                                .addComponent(lblOblozenie)))
                        .addGap(0, 222, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOblozenie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //michal ppk sortowanie!
        parentFrame.sporzadzRaportOblozenie(null);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOblozenie;
    // End of variables declaration//GEN-END:variables

    public void updateJpanel(Date dataOd, Date dataDo, ArrayList<String> hotele, int standard, int goscie, String sort) {
        p.removeAll();
        OblozenieKlasa.getInstance().clearAll();
        MySql.getInstance().raportOblozenie(dataOd, dataDo, hotele, standard, goscie, sort);
    }

    public void renderHotele() {
        OblozenieKlasa obk = OblozenieKlasa.getInstance();
        ArrayList<HotelObl> hotele = obk.getHotele();
        int size = hotele.size();
        
        p.setLayout(new GridLayout(size, 1));
        int oblozenieInt = 0;
        for (int i = 0; i < size; ++i) {
            hotele.get(i).renderuj();
            oblozenieInt += hotele.get(i).getOblozenie();
            p.add(hotele.get(i));
        }
        lblOblozenie.setText("Sumaryczne obłożenie: "+oblozenieInt);
        jScrollPane1.setViewportView(p);
    }
}
