/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package psbd.projekt.panes;

import psbd.projekt.utils.Utils;

/**
 *
 * @author Michal
 */
public class PokojObl extends javax.swing.JPanel {
    
    int ile_rezerwacji = 0;
    
    /**
     * Creates new form PokojNiezre
     */
    PokojObl(int standard, int liczba_osob, int ile_rezerwacji) {
        initComponents();
        lblOblozenie.setText("Obłożenie: " + ile_rezerwacji);
        lblMax.setText("Ilość osób: " +liczba_osob);
        lblStandard1.setText(Utils.mapStandard.get(standard));
        this.ile_rezerwacji = ile_rezerwacji;
    }
    
    public int getOblozenie(){
        return ile_rezerwacji;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMax = new javax.swing.JLabel();
        lblOblozenie = new javax.swing.JLabel();
        lblStandard1 = new javax.swing.JLabel();

        lblMax.setText("Liczba osób: X/Y");

        lblOblozenie.setText("Oblozenie");

        lblStandard1.setText("Standard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStandard1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMax, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOblozenie, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblStandard1)
                .addComponent(lblMax)
                .addComponent(lblOblozenie))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblOblozenie;
    private javax.swing.JLabel lblStandard1;
    // End of variables declaration//GEN-END:variables
}
