/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psbd.projekt.model;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import psbd.projekt.MainWindow;
import psbd.projekt.classes.Pracownik;
import psbd.projekt.utils.MySql;

/**
 *
 * @author Michal
 */
public class Hotel extends javax.swing.JPanel {

    short iloscGwiazdek;
    String nazwa;
    int id;
    ArrayList<Pokoj> pokoje = new ArrayList<>();
    JPanel p = new JPanel();
    private MainWindow parentFrame;
    int id_rezerwacji;

    /**
     * Creates new form Hotel
     */
    public Hotel(short liczbaGwiazdek, String nazwa, int id, int id_rezerwacji, String status, MainWindow parentFrame) {
        initComponents();
        this.iloscGwiazdek = liczbaGwiazdek;
        this.nazwa = nazwa;
        this.id = id;
        this.parentFrame = parentFrame;
        this.id_rezerwacji = id_rezerwacji;

        lblNazwa.setText(nazwa);
        StringBuilder sb = new StringBuilder("Liczba gwiazdek: ");
        String str = "Liczba gwiazdek: ";
        for (int i = 0; i < liczbaGwiazdek; ++i) {
            sb.append("*");
            str += "*";
        }
        lblLiczbaGwiazdek.setText(sb.toString());
        lblNrRezerwacji.setText("Numer rezerwacji: " + id_rezerwacji);
        
        cbStatus.setSelectedItem(status);
    }

    public void addPokojDoHotelu(int idPokoju, int nrPokoju, float cena, short standard, short maxOsob, short liczbaPomieszczen) {
        pokoje.add(new Pokoj(idPokoju,
                this,
                nrPokoju,
                cena,
                standard,
                maxOsob,
                liczbaPomieszczen
        ));
    }

    public int getIdHotelu() {
        return id;
    }

    public void drawPokoje() {
        int size = pokoje.size();
        p.setLayout(new GridLayout(size, 1));
        for (int i = 0; i < size; ++i) {
            p.add(pokoje.get(i));
        }
        jspPokoje.setViewportView(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazwa = new javax.swing.JLabel();
        lblLiczbaGwiazdek = new javax.swing.JLabel();
        btnRezerwuj = new javax.swing.JButton();
        jspPokoje = new javax.swing.JScrollPane();
        lblNrRezerwacji = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox();

        lblNazwa.setText("Nazwa");

        lblLiczbaGwiazdek.setText("Liczba gwiazdek:");

        btnRezerwuj.setText("Zapisz");
        btnRezerwuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezerwujActionPerformed(evt);
            }
        });

        lblNrRezerwacji.setText("Nr rezerwacji");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "aktywna", "nieaktywna", "kara", "zameldowany", "wymeldowany" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspPokoje)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNazwa)
                        .addGap(18, 18, 18)
                        .addComponent(lblLiczbaGwiazdek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(btnRezerwuj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNrRezerwacji)
                        .addGap(18, 18, 18)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazwa)
                    .addComponent(lblLiczbaGwiazdek)
                    .addComponent(btnRezerwuj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrRezerwacji)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspPokoje, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRezerwujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezerwujActionPerformed
        String status = (String)cbStatus.getSelectedItem();
        MySql.getInstance().zmienStatus(status,id_rezerwacji);
    }//GEN-LAST:event_btnRezerwujActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRezerwuj;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JScrollPane jspPokoje;
    private javax.swing.JLabel lblLiczbaGwiazdek;
    private javax.swing.JLabel lblNazwa;
    private javax.swing.JLabel lblNrRezerwacji;
    // End of variables declaration//GEN-END:variables

    public Object[][] getZarezerwowanePokoje() {
        ArrayList<ArrayList<Object>> listaPokoje = new ArrayList<ArrayList<Object>>();
        for (Pokoj p : pokoje) {
            Object[] pokojDane = p.getIdileOsobArray();
            if ((int) pokojDane[1] > 0) {
                ArrayList<Object> pokoj = new ArrayList<>();
                pokoj.add(pokojDane[0]);
                pokoj.add(pokojDane[1]);
                pokoj.add(pokojDane[2]);
                listaPokoje.add(pokoj);
            }
        }
        int size = listaPokoje.size();
        Object[][] toRet = new Object[size][3];
        for (int i = 0; i < size; ++i) {
            for (int j = 0; j < 3; ++j) {
                toRet[i][j] = listaPokoje.get(i).get(j);
            }
        }
        return toRet;
    }

    int getIdRezerwacji() {
        return id_rezerwacji;
    }
}
